version: "2"
services:
    haproxy:
        image: haproxy:alpine
        volumes:
            - ./haproxy:/usr/local/etc/haproxy
        links:
            - weba
            - webb
        ports:
            - "8080:80"
            - "70:70"
        expose:
            - "80"
            - "70"

    weba:
        build: .
        command: npm start
        volumes:
            - .:/usr/src/app
        links:
            - mongodb
        depends_on:
            - mongodb

    webb:
        build: .
        command: npm start
        volumes:
            - .:/usr/src/app
        links:
            - mongodb
        depends_on:
            - mongodb

    mongodb:
        image: mongo:latest
        container_name: "mongodb"
        environment:
            - MONGO_DATA_DIR=/data/db
            - MONGO_LOG_DIR=/dev/null
        volumes:
            - ./data/db:/data/db
        ports:
            - 27018:27017
        command: mongod --smallfiles --logpath=/dev/null
